### ISSUE TITLE
graceful exit with bad API key

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/wifi-geolocation#9]
When API key is left to default value, the program outputs the following:
```
> Initializing display
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.s
  InsecureRequestWarning)
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    __main__()
  File "main.py", line 30, in __main__
    gps_check = json.loads(gps)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

It should display a message saying that there was no response from the API or something along those lines.

**Comment by greenbreakfast** [comment]
requires `config.json` file to hold the API key. if this file is not present, program exits
